<h1>Rede Neural Artificial #00</h1>

#IMPORTANDO BIBLIOTECAS E PREPARANDO DATASET:

In [1]:
import keras
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

Using TensorFlow backend.


In [2]:
x.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)
0               5.1              3.5               1.4              0.2
1               4.9              3.0               1.4              0.2
2               4.7              3.2               1.3              0.2
3               4.6              3.1               1.5              0.2
4               5.0              3.6               1.4              0.2

In [3]:
y.value_counts()

2    50
1    50
0    50
dtype: int64

In [4]:
import keras
from keras.utils import np_utils
y_convertido = np_utils.to_categorical(y)

#PREPRANDO MINHA REDE

In [5]:
y_convertido

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [6]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y_convertido, test_size = 0.3)

In [7]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [8]:
modelo = Sequential()
modelo.add(Dense(10, input_dim=4, kernel_initializer='normal', activation='relu'))
modelo.add(Dense(3, kernel_initializer='normal', activation='softmax'))

W0316 00:46:12.327291 140578552796544 deprecation_wrapper.py:119] From /home/george/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0316 00:46:12.664175 140578552796544 deprecation_wrapper.py:119] From /home/george/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0316 00:46:12.672796 140578552796544 deprecation_wrapper.py:119] From /home/george/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:4115: The name tf.random_normal is deprecated. Please use tf.random.normal instead.



In [9]:
otimizador = SGD()

In [10]:
modelo.compile(loss='categorical_crossentropy', optimizer=otimizador, metrics=['acc'])

W0316 00:46:13.267205 140578552796544 deprecation_wrapper.py:119] From /home/george/anaconda2/lib/python2.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0316 00:46:13.283767 140578552796544 deprecation_wrapper.py:119] From /home/george/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [11]:
#verbode 1 imprimiria as informções de cada época
modelo.fit(x_treino, y_treino, epochs=1000, batch_size=105, validation_data=(x_teste, y_teste), verbose=1) 

W0316 00:46:14.093151 140578552796544 deprecation.py:323] From /home/george/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_grad.py:1250: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0316 00:46:14.146819 140578552796544 deprecation_wrapper.py:119] From /home/george/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Train on 105 samples, validate on 45 samples
Epoch 1/1000
105/105 [==============================] - 1s 8ms/step - loss: 1.1011 - acc: 0.3714 - val_loss: 1.1084 - val_acc: 0.2444
Epoch 2/1000
105/105 [==============================] - 0s 22us/step - loss: 1.1007 - acc: 0.3714 - val_loss: 1.1082 - val_acc: 0.2444
Epoch 3/1000
105/105 [==============================] - 0s 69us/step - loss: 1.1003 - acc: 0.3714 - val_loss: 1.1079 - val_acc: 0.2444
Epoch 4/1000
105/105 [==============================] - 0s 29us/step - loss: 1.0999 - acc: 0.3714 - val_loss: 1.1077 - val_acc: 0.2444
Epoch 5/1000
105/105 [==============================] - 0s 29us/step - loss: 1.0996 - acc: 0.3714 - val_loss: 1.1074 - val_acc: 0.2444
Epoch 6/1000
105/105 [==============================] - 0s 36us/step - loss: 1.0992 - acc: 0.3714 - val_loss: 1.1072 - val_acc: 0.2444
Epoch 7/1000
105/105 [==============================] - 0s 40us/step - loss: 1.0989 - acc: 0.3714 - val_loss: 1.1070 - val_acc: 0.2444
Epoch 8/100

Epoch 61/1000
105/105 [==============================] - 0s 40us/step - loss: 1.0806 - acc: 0.3714 - val_loss: 1.0956 - val_acc: 0.2444
Epoch 62/1000
105/105 [==============================] - 0s 23us/step - loss: 1.0802 - acc: 0.3714 - val_loss: 1.0953 - val_acc: 0.2444
Epoch 63/1000
105/105 [==============================] - 0s 17us/step - loss: 1.0798 - acc: 0.3714 - val_loss: 1.0950 - val_acc: 0.2444
Epoch 64/1000
105/105 [==============================] - 0s 66us/step - loss: 1.0794 - acc: 0.3714 - val_loss: 1.0948 - val_acc: 0.2444
Epoch 65/1000
105/105 [==============================] - 0s 33us/step - loss: 1.0791 - acc: 0.3714 - val_loss: 1.0945 - val_acc: 0.2444
Epoch 66/1000
105/105 [==============================] - 0s 59us/step - loss: 1.0787 - acc: 0.3714 - val_loss: 1.0942 - val_acc: 0.2444
Epoch 67/1000
105/105 [==============================] - 0s 33us/step - loss: 1.0783 - acc: 0.3714 - val_loss: 1.0939 - val_acc: 0.2444
Epoch 68/1000
105/105 [=========================

105/105 [==============================] - 0s 39us/step - loss: 1.0510 - acc: 0.3714 - val_loss: 1.0697 - val_acc: 0.2444
Epoch 122/1000
105/105 [==============================] - 0s 52us/step - loss: 1.0503 - acc: 0.3714 - val_loss: 1.0691 - val_acc: 0.2444
Epoch 123/1000
105/105 [==============================] - 0s 20us/step - loss: 1.0497 - acc: 0.3714 - val_loss: 1.0684 - val_acc: 0.2444
Epoch 124/1000
105/105 [==============================] - 0s 16us/step - loss: 1.0490 - acc: 0.3714 - val_loss: 1.0678 - val_acc: 0.2444
Epoch 125/1000
105/105 [==============================] - 0s 66us/step - loss: 1.0483 - acc: 0.3714 - val_loss: 1.0671 - val_acc: 0.2444
Epoch 126/1000
105/105 [==============================] - 0s 61us/step - loss: 1.0476 - acc: 0.3714 - val_loss: 1.0664 - val_acc: 0.2444
Epoch 127/1000
105/105 [==============================] - 0s 45us/step - loss: 1.0468 - acc: 0.3714 - val_loss: 1.0657 - val_acc: 0.2444
Epoch 128/1000
105/105 [==============================] 

Epoch 181/1000
105/105 [==============================] - 0s 79us/step - loss: 0.9930 - acc: 0.7333 - val_loss: 1.0133 - val_acc: 0.4889
Epoch 182/1000
105/105 [==============================] - 0s 40us/step - loss: 0.9917 - acc: 0.7333 - val_loss: 1.0120 - val_acc: 0.5111
Epoch 183/1000
105/105 [==============================] - 0s 56us/step - loss: 0.9904 - acc: 0.7333 - val_loss: 1.0107 - val_acc: 0.5111
Epoch 184/1000
105/105 [==============================] - 0s 34us/step - loss: 0.9890 - acc: 0.7333 - val_loss: 1.0094 - val_acc: 0.5111
Epoch 185/1000
105/105 [==============================] - 0s 25us/step - loss: 0.9876 - acc: 0.7333 - val_loss: 1.0080 - val_acc: 0.5111
Epoch 186/1000
105/105 [==============================] - 0s 17us/step - loss: 0.9862 - acc: 0.7333 - val_loss: 1.0067 - val_acc: 0.5111
Epoch 187/1000
105/105 [==============================] - 0s 16us/step - loss: 0.9848 - acc: 0.7333 - val_loss: 1.0054 - val_acc: 0.5111
Epoch 188/1000
105/105 [=================

Epoch 241/1000
105/105 [==============================] - 0s 65us/step - loss: 0.8893 - acc: 0.7333 - val_loss: 0.9117 - val_acc: 0.5111
Epoch 242/1000
105/105 [==============================] - 0s 71us/step - loss: 0.8872 - acc: 0.7333 - val_loss: 0.9097 - val_acc: 0.5111
Epoch 243/1000
105/105 [==============================] - 0s 48us/step - loss: 0.8851 - acc: 0.7333 - val_loss: 0.9076 - val_acc: 0.5111
Epoch 244/1000
105/105 [==============================] - 0s 73us/step - loss: 0.8830 - acc: 0.7333 - val_loss: 0.9055 - val_acc: 0.5111
Epoch 245/1000
105/105 [==============================] - 0s 96us/step - loss: 0.8809 - acc: 0.7333 - val_loss: 0.9034 - val_acc: 0.5111
Epoch 246/1000
105/105 [==============================] - 0s 58us/step - loss: 0.8788 - acc: 0.7333 - val_loss: 0.9013 - val_acc: 0.5111
Epoch 247/1000
105/105 [==============================] - 0s 34us/step - loss: 0.8767 - acc: 0.7333 - val_loss: 0.8992 - val_acc: 0.5111
Epoch 248/1000
105/105 [=================

Epoch 301/1000
105/105 [==============================] - 0s 69us/step - loss: 0.7547 - acc: 0.7714 - val_loss: 0.7828 - val_acc: 0.6444
Epoch 302/1000
105/105 [==============================] - 0s 27us/step - loss: 0.7524 - acc: 0.7714 - val_loss: 0.7807 - val_acc: 0.6667
Epoch 303/1000
105/105 [==============================] - 0s 25us/step - loss: 0.7501 - acc: 0.7905 - val_loss: 0.7786 - val_acc: 0.6667
Epoch 304/1000
105/105 [==============================] - 0s 52us/step - loss: 0.7479 - acc: 0.7905 - val_loss: 0.7765 - val_acc: 0.6667
Epoch 305/1000
105/105 [==============================] - 0s 48us/step - loss: 0.7456 - acc: 0.7905 - val_loss: 0.7744 - val_acc: 0.6667
Epoch 306/1000
105/105 [==============================] - 0s 22us/step - loss: 0.7433 - acc: 0.8000 - val_loss: 0.7723 - val_acc: 0.6667
Epoch 307/1000
105/105 [==============================] - 0s 46us/step - loss: 0.7410 - acc: 0.8286 - val_loss: 0.7702 - val_acc: 0.6667
Epoch 308/1000
105/105 [=================

Epoch 361/1000
105/105 [==============================] - 0s 67us/step - loss: 0.6312 - acc: 0.9619 - val_loss: 0.6695 - val_acc: 0.9111
Epoch 362/1000
105/105 [==============================] - 0s 34us/step - loss: 0.6294 - acc: 0.9619 - val_loss: 0.6679 - val_acc: 0.9111
Epoch 363/1000
105/105 [==============================] - 0s 93us/step - loss: 0.6277 - acc: 0.9619 - val_loss: 0.6663 - val_acc: 0.9111
Epoch 364/1000
105/105 [==============================] - 0s 58us/step - loss: 0.6260 - acc: 0.9619 - val_loss: 0.6648 - val_acc: 0.9111
Epoch 365/1000
105/105 [==============================] - 0s 22us/step - loss: 0.6243 - acc: 0.9619 - val_loss: 0.6632 - val_acc: 0.9111
Epoch 366/1000
105/105 [==============================] - 0s 26us/step - loss: 0.6226 - acc: 0.9619 - val_loss: 0.6617 - val_acc: 0.9111
Epoch 367/1000
105/105 [==============================] - 0s 24us/step - loss: 0.6209 - acc: 0.9619 - val_loss: 0.6602 - val_acc: 0.9111
Epoch 368/1000
105/105 [=================

Epoch 421/1000
105/105 [==============================] - 0s 26us/step - loss: 0.5450 - acc: 0.9905 - val_loss: 0.5919 - val_acc: 0.8889
Epoch 422/1000
105/105 [==============================] - 0s 19us/step - loss: 0.5439 - acc: 0.9905 - val_loss: 0.5909 - val_acc: 0.8889
Epoch 423/1000
105/105 [==============================] - 0s 25us/step - loss: 0.5428 - acc: 0.9905 - val_loss: 0.5898 - val_acc: 0.8889
Epoch 424/1000
105/105 [==============================] - 0s 43us/step - loss: 0.5416 - acc: 0.9905 - val_loss: 0.5888 - val_acc: 0.8889
Epoch 425/1000
105/105 [==============================] - 0s 72us/step - loss: 0.5405 - acc: 0.9905 - val_loss: 0.5878 - val_acc: 0.8889
Epoch 426/1000
105/105 [==============================] - 0s 38us/step - loss: 0.5394 - acc: 0.9905 - val_loss: 0.5868 - val_acc: 0.8889
Epoch 427/1000
105/105 [==============================] - 0s 27us/step - loss: 0.5383 - acc: 0.9905 - val_loss: 0.5858 - val_acc: 0.8889
Epoch 428/1000
105/105 [=================

Epoch 481/1000
105/105 [==============================] - 0s 21us/step - loss: 0.4882 - acc: 0.9905 - val_loss: 0.5406 - val_acc: 0.8889
Epoch 482/1000
105/105 [==============================] - 0s 22us/step - loss: 0.4874 - acc: 0.9905 - val_loss: 0.5398 - val_acc: 0.8889
Epoch 483/1000
105/105 [==============================] - 0s 53us/step - loss: 0.4866 - acc: 0.9905 - val_loss: 0.5391 - val_acc: 0.8889
Epoch 484/1000
105/105 [==============================] - 0s 48us/step - loss: 0.4858 - acc: 0.9905 - val_loss: 0.5384 - val_acc: 0.8889
Epoch 485/1000
105/105 [==============================] - 0s 58us/step - loss: 0.4851 - acc: 0.9905 - val_loss: 0.5377 - val_acc: 0.8889
Epoch 486/1000
105/105 [==============================] - 0s 23us/step - loss: 0.4843 - acc: 0.9905 - val_loss: 0.5370 - val_acc: 0.8889
Epoch 487/1000
105/105 [==============================] - 0s 36us/step - loss: 0.4836 - acc: 0.9905 - val_loss: 0.5363 - val_acc: 0.8889
Epoch 488/1000
105/105 [=================

Epoch 541/1000
105/105 [==============================] - 0s 18us/step - loss: 0.4476 - acc: 0.9905 - val_loss: 0.5029 - val_acc: 0.8889
Epoch 542/1000
105/105 [==============================] - 0s 28us/step - loss: 0.4470 - acc: 0.9905 - val_loss: 0.5023 - val_acc: 0.8889
Epoch 543/1000
105/105 [==============================] - 0s 21us/step - loss: 0.4464 - acc: 0.9905 - val_loss: 0.5018 - val_acc: 0.8889
Epoch 544/1000
105/105 [==============================] - 0s 16us/step - loss: 0.4458 - acc: 0.9905 - val_loss: 0.5012 - val_acc: 0.8889
Epoch 545/1000
105/105 [==============================] - 0s 23us/step - loss: 0.4452 - acc: 0.9905 - val_loss: 0.5007 - val_acc: 0.8889
Epoch 546/1000
105/105 [==============================] - 0s 44us/step - loss: 0.4446 - acc: 0.9905 - val_loss: 0.5001 - val_acc: 0.8889
Epoch 547/1000
105/105 [==============================] - 0s 16us/step - loss: 0.4441 - acc: 0.9905 - val_loss: 0.4995 - val_acc: 0.8889
Epoch 548/1000
105/105 [=================

Epoch 601/1000
105/105 [==============================] - 0s 26us/step - loss: 0.4153 - acc: 0.9905 - val_loss: 0.4719 - val_acc: 0.8889
Epoch 602/1000
105/105 [==============================] - 0s 82us/step - loss: 0.4149 - acc: 0.9905 - val_loss: 0.4714 - val_acc: 0.8889
Epoch 603/1000
105/105 [==============================] - 0s 19us/step - loss: 0.4144 - acc: 0.9905 - val_loss: 0.4709 - val_acc: 0.8889
Epoch 604/1000
105/105 [==============================] - 0s 89us/step - loss: 0.4139 - acc: 0.9905 - val_loss: 0.4704 - val_acc: 0.8889
Epoch 605/1000
105/105 [==============================] - 0s 19us/step - loss: 0.4134 - acc: 0.9905 - val_loss: 0.4700 - val_acc: 0.8889
Epoch 606/1000
105/105 [==============================] - 0s 18us/step - loss: 0.4129 - acc: 0.9905 - val_loss: 0.4695 - val_acc: 0.8889
Epoch 607/1000
105/105 [==============================] - 0s 64us/step - loss: 0.4124 - acc: 0.9905 - val_loss: 0.4690 - val_acc: 0.8889
Epoch 608/1000
105/105 [=================

Epoch 661/1000
105/105 [==============================] - 0s 65us/step - loss: 0.3875 - acc: 0.9905 - val_loss: 0.4443 - val_acc: 0.8889
Epoch 662/1000
105/105 [==============================] - 0s 24us/step - loss: 0.3871 - acc: 0.9905 - val_loss: 0.4438 - val_acc: 0.8889
Epoch 663/1000
105/105 [==============================] - 0s 49us/step - loss: 0.3866 - acc: 0.9905 - val_loss: 0.4434 - val_acc: 0.8889
Epoch 664/1000
105/105 [==============================] - 0s 22us/step - loss: 0.3862 - acc: 0.9905 - val_loss: 0.4429 - val_acc: 0.8889
Epoch 665/1000
105/105 [==============================] - 0s 25us/step - loss: 0.3857 - acc: 0.9905 - val_loss: 0.4425 - val_acc: 0.8889
Epoch 666/1000
105/105 [==============================] - 0s 35us/step - loss: 0.3853 - acc: 0.9905 - val_loss: 0.4420 - val_acc: 0.8889
Epoch 667/1000
105/105 [==============================] - 0s 23us/step - loss: 0.3849 - acc: 0.9905 - val_loss: 0.4416 - val_acc: 0.8889
Epoch 668/1000
105/105 [=================

Epoch 721/1000
105/105 [==============================] - 0s 16us/step - loss: 0.3621 - acc: 0.9905 - val_loss: 0.4185 - val_acc: 0.8889
Epoch 722/1000
105/105 [==============================] - 0s 18us/step - loss: 0.3617 - acc: 0.9905 - val_loss: 0.4180 - val_acc: 0.8889
Epoch 723/1000
105/105 [==============================] - 0s 41us/step - loss: 0.3613 - acc: 0.9905 - val_loss: 0.4176 - val_acc: 0.8889
Epoch 724/1000
105/105 [==============================] - 0s 26us/step - loss: 0.3609 - acc: 0.9905 - val_loss: 0.4172 - val_acc: 0.8889
Epoch 725/1000
105/105 [==============================] - 0s 53us/step - loss: 0.3605 - acc: 0.9905 - val_loss: 0.4168 - val_acc: 0.8889
Epoch 726/1000
105/105 [==============================] - 0s 43us/step - loss: 0.3600 - acc: 0.9905 - val_loss: 0.4164 - val_acc: 0.8889
Epoch 727/1000
105/105 [==============================] - 0s 64us/step - loss: 0.3596 - acc: 0.9905 - val_loss: 0.4159 - val_acc: 0.8889
Epoch 728/1000
105/105 [=================

Epoch 781/1000
105/105 [==============================] - 0s 39us/step - loss: 0.3382 - acc: 0.9905 - val_loss: 0.3939 - val_acc: 0.8889
Epoch 782/1000
105/105 [==============================] - 0s 101us/step - loss: 0.3379 - acc: 0.9905 - val_loss: 0.3935 - val_acc: 0.8889
Epoch 783/1000
105/105 [==============================] - 0s 19us/step - loss: 0.3375 - acc: 0.9905 - val_loss: 0.3931 - val_acc: 0.8889
Epoch 784/1000
105/105 [==============================] - 0s 41us/step - loss: 0.3371 - acc: 0.9905 - val_loss: 0.3927 - val_acc: 0.8889
Epoch 785/1000
105/105 [==============================] - 0s 44us/step - loss: 0.3367 - acc: 0.9905 - val_loss: 0.3923 - val_acc: 0.8889
Epoch 786/1000
105/105 [==============================] - 0s 72us/step - loss: 0.3363 - acc: 0.9905 - val_loss: 0.3919 - val_acc: 0.8889
Epoch 787/1000
105/105 [==============================] - 0s 26us/step - loss: 0.3359 - acc: 0.9905 - val_loss: 0.3915 - val_acc: 0.8889
Epoch 788/1000
105/105 [================

Epoch 841/1000
105/105 [==============================] - 0s 41us/step - loss: 0.3157 - acc: 0.9905 - val_loss: 0.3705 - val_acc: 0.8889
Epoch 842/1000
105/105 [==============================] - 0s 24us/step - loss: 0.3153 - acc: 0.9905 - val_loss: 0.3701 - val_acc: 0.8889
Epoch 843/1000
105/105 [==============================] - 0s 37us/step - loss: 0.3149 - acc: 0.9905 - val_loss: 0.3698 - val_acc: 0.8889
Epoch 844/1000
105/105 [==============================] - 0s 32us/step - loss: 0.3146 - acc: 0.9905 - val_loss: 0.3694 - val_acc: 0.8889
Epoch 845/1000
105/105 [==============================] - 0s 52us/step - loss: 0.3142 - acc: 0.9905 - val_loss: 0.3690 - val_acc: 0.8889
Epoch 846/1000
105/105 [==============================] - 0s 29us/step - loss: 0.3138 - acc: 0.9905 - val_loss: 0.3686 - val_acc: 0.8889
Epoch 847/1000
105/105 [==============================] - 0s 91us/step - loss: 0.3135 - acc: 0.9905 - val_loss: 0.3683 - val_acc: 0.8889
Epoch 848/1000
105/105 [=================

Epoch 901/1000
105/105 [==============================] - 0s 31us/step - loss: 0.2943 - acc: 0.9905 - val_loss: 0.3485 - val_acc: 0.9333
Epoch 902/1000
105/105 [==============================] - 0s 21us/step - loss: 0.2940 - acc: 0.9905 - val_loss: 0.3481 - val_acc: 0.9333
Epoch 903/1000
105/105 [==============================] - 0s 47us/step - loss: 0.2936 - acc: 0.9905 - val_loss: 0.3477 - val_acc: 0.9333
Epoch 904/1000
105/105 [==============================] - 0s 30us/step - loss: 0.2933 - acc: 0.9905 - val_loss: 0.3474 - val_acc: 0.9333
Epoch 905/1000
105/105 [==============================] - 0s 30us/step - loss: 0.2930 - acc: 0.9905 - val_loss: 0.3470 - val_acc: 0.9333
Epoch 906/1000
105/105 [==============================] - 0s 51us/step - loss: 0.2926 - acc: 0.9905 - val_loss: 0.3467 - val_acc: 0.9333
Epoch 907/1000
105/105 [==============================] - 0s 33us/step - loss: 0.2923 - acc: 0.9905 - val_loss: 0.3463 - val_acc: 0.9333
Epoch 908/1000
105/105 [=================

Epoch 961/1000
105/105 [==============================] - 0s 18us/step - loss: 0.2743 - acc: 0.9905 - val_loss: 0.3278 - val_acc: 0.9333
Epoch 962/1000
105/105 [==============================] - 0s 35us/step - loss: 0.2740 - acc: 0.9905 - val_loss: 0.3274 - val_acc: 0.9333
Epoch 963/1000
105/105 [==============================] - 0s 26us/step - loss: 0.2736 - acc: 0.9905 - val_loss: 0.3271 - val_acc: 0.9333
Epoch 964/1000
105/105 [==============================] - 0s 34us/step - loss: 0.2733 - acc: 0.9905 - val_loss: 0.3268 - val_acc: 0.9333
Epoch 965/1000
105/105 [==============================] - 0s 37us/step - loss: 0.2730 - acc: 0.9905 - val_loss: 0.3264 - val_acc: 0.9333
Epoch 966/1000
105/105 [==============================] - 0s 29us/step - loss: 0.2727 - acc: 0.9905 - val_loss: 0.3261 - val_acc: 0.9333
Epoch 967/1000
105/105 [==============================] - 0s 24us/step - loss: 0.2724 - acc: 0.9905 - val_loss: 0.3258 - val_acc: 0.9333
Epoch 968/1000
105/105 [=================

In [12]:
predicoes = modelo.predict(x_teste)
print predicoes

[[1.0127185e-03 3.5763648e-01 6.4135081e-01]
 [1.0948471e-03 3.0989319e-01 6.8901199e-01]
 [3.7105205e-03 4.9350929e-01 5.0278014e-01]
 [4.4236472e-03 5.0979811e-01 4.8577815e-01]
 [9.3686128e-01 6.2659666e-02 4.7915327e-04]
 [2.6677951e-04 2.4502262e-01 7.5471056e-01]
 [2.1772512e-04 2.1087298e-01 7.8890926e-01]
 [9.9540548e-06 7.6512806e-02 9.2347729e-01]
 [1.9036870e-02 6.5824074e-01 3.2272232e-01]
 [2.6128177e-02 7.8765047e-01 1.8622138e-01]
 [8.3366985e-04 3.1904513e-01 6.8012118e-01]
 [8.2825607e-04 2.8828958e-01 7.1088213e-01]
 [9.6557695e-01 3.4305815e-02 1.1729622e-04]
 [3.7983491e-03 4.9284589e-01 5.0335574e-01]
 [9.4227332e-01 5.7438888e-02 2.8773019e-04]
 [2.4445108e-04 2.0996171e-01 7.8979385e-01]
 [5.8165740e-04 2.4362509e-01 7.5579321e-01]
 [1.1605179e-02 6.0987777e-01 3.7851700e-01]
 [2.9334301e-04 2.2482008e-01 7.7488661e-01]
 [5.5724876e-03 5.4368281e-01 4.5074478e-01]
 [7.3289440e-04 3.4453830e-01 6.5472883e-01]
 [1.2166006e-02 7.0369953e-01 2.8413445e-01]
 [1.914537

In [13]:
import numpy as np
np.set_printoptions(formatter={'float':lambda x: "{0:0.2f}".format(x)})
print predicoes

[[0.00 0.36 0.64]
 [0.00 0.31 0.69]
 [0.00 0.49 0.50]
 [0.00 0.51 0.49]
 [0.94 0.06 0.00]
 [0.00 0.25 0.75]
 [0.00 0.21 0.79]
 [0.00 0.08 0.92]
 [0.02 0.66 0.32]
 [0.03 0.79 0.19]
 [0.00 0.32 0.68]
 [0.00 0.29 0.71]
 [0.97 0.03 0.00]
 [0.00 0.49 0.50]
 [0.94 0.06 0.00]
 [0.00 0.21 0.79]
 [0.00 0.24 0.76]
 [0.01 0.61 0.38]
 [0.00 0.22 0.77]
 [0.01 0.54 0.45]
 [0.00 0.34 0.65]
 [0.01 0.70 0.28]
 [0.00 0.32 0.68]
 [0.00 0.17 0.83]
 [0.00 0.28 0.72]
 [0.00 0.46 0.53]
 [0.00 0.36 0.64]
 [0.04 0.73 0.23]
 [0.97 0.03 0.00]
 [0.95 0.05 0.00]
 [0.00 0.42 0.58]
 [0.00 0.23 0.77]
 [0.92 0.08 0.00]
 [0.93 0.07 0.00]
 [0.01 0.50 0.49]
 [0.90 0.10 0.00]
 [0.00 0.37 0.63]
 [0.05 0.77 0.18]
 [0.98 0.02 0.00]
 [0.09 0.73 0.18]
 [0.17 0.73 0.10]
 [0.99 0.01 0.00]
 [0.94 0.06 0.00]
 [0.97 0.03 0.00]
 [0.00 0.50 0.49]]
