<h3>Aula 00 - Olá Mundo!<h3/>

In [61]:
import tensorflow as tf

In [62]:
frase = tf.constant('Olá mundo')
#with tf.Session() as ss:
#    rodar = ss.run(frase)
#print(rodar)

#outra opção:
print(tf.Session().run(frase))    

Olá mundo


In [63]:
print(frase) #variável frase é um tensor

Tensor("Const_56:0", shape=(), dtype=string)


<h3>Aula 01 - Grafo Computacional: Pensando sobre Processamento Paralelo <h3/>

In [64]:
a = tf.constant(5)
b = tf.constant(3)
c = tf.constant(2)

d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)

sess = tf.Session()
saida = sess.run(f) #aqui as variáveis recebem os valores pq uma depende da outra
sess.close() #boa prática

In [65]:
print(saida)

10


In [66]:
print(f) #as variáveis são tensores

Tensor("Sub_9:0", shape=(), dtype=int32)


<h3>Aula 02 - O que são Tensores?<h3/>

In [67]:
#Aqui tudo são Tensores
a = tf.constant(2) #1x1
b = tf.constant([2,1,5,6,7]) #1xn
c = tf.constant([[2,1,5,6,7],[2,1,5,6,7]]) #mxn

sess = tf.Session()
saida = sess.run(c)
sess.close()

In [68]:
print(saida)

[[2 1 5 6 7]
 [2 1 5 6 7]]


Comparação com Numpy

In [69]:
import numpy as np
a1 = np.array(2)
b1 = np.array([1,4,6,2,9])
c1 = np.array([[1,2,3],[4,5,6]])

In [70]:
print(c.shape)

(2, 5)


In [71]:
print(c1.shape)

(2, 3)


In [72]:
#Type -> identifica sozinho
const = tf.constant(4.78)
print(const)

Tensor("Const_63:0", shape=(), dtype=float32)


In [73]:
#Ou defina
const = tf.constant(4, dtype=tf.float64)
print(const)

Tensor("Const_64:0", shape=(), dtype=float64)


<h3>Aula 03 - Multiplicação de matrizes<h3/>

In [74]:
A = tf.constant([[1,2,3],[9,0,8]])
B = tf.constant([[1,2],[9,0],[1,1]])

In [77]:
print B

Tensor("Const_66:0", shape=(3, 2), dtype=int32)


In [80]:
print(saida)

[[2 1 5 6 7]
 [2 1 5 6 7]]


In [92]:
#Usando expand
x = tf.constant([0,1,0])
sess.run(x)

array([0, 1, 0], dtype=int32)

In [93]:
x.shape

TensorShape([Dimension(3)])

In [97]:
x = tf.expand_dims(x,1) #AQUI

In [98]:
x.shape 

TensorShape([Dimension(3), Dimension(1)])

In [99]:
resultado2 = tf.matmul(A,x)

In [100]:
print(sess.run(resultado2))

[[2]
 [0]]


Transposta

In [101]:
print(sess.run(A))

[[1 2 3]
 [9 0 8]]


In [102]:
transposta = tf.transpose(A)

In [104]:
print(sess.run(transposta))

[[1 9]
 [2 0]
 [3 8]]


<h3>Aula 04 - Variáveis no Tensor flow<h3/>

In [105]:
variavel = tf.Variable(7)

In [107]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    rodar = sess.run(variavel)
print(rodar)

7


In [108]:
matriz = tf.random_normal((3,5),0,1) #(shape, média, desvio_padrão)

In [109]:
variavel2 = tf.Variable(matriz)
print(variavel2)

<tf.Variable 'Variable_1:0' shape=(3, 5) dtype=float32_ref>


In [111]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    rodar = sess.run(variavel2)
print(rodar)

[[ 0.72136277 -0.10628515  0.5569532  -0.83018893  0.1730272 ]
 [ 1.57901    -0.2241401   0.43604577  2.9345324   1.1493737 ]
 [-0.77825487  0.29126006  0.12586072  1.0651444  -0.06758285]]


<h3>Aula 05 - Placeholders<h3/>

In [116]:
dados_x = np.random.randn(4,8)
dados_w = np.random.randn(8,2)

b = tf.random_normal((4,2),0,1)

x = tf.placeholder(tf.float32, shape=(4,8))
w = tf.placeholder(tf.float32, shape=(8,2))
operacao = tf.matmul(x,w)+b
maximo = tf.reduce_max(operacao)

In [117]:
with tf.Session() as sess:
    saida1 = sess.run(operacao, feed_dict = {x: dados_x, w: dados_w})
    saida2 = sess.run(maximo, feed_dict = {x: dados_x, w: dados_w})

In [118]:
print saida1

[[ 0.41015863 -2.9372668 ]
 [ 5.3692226   0.91463006]
 [-0.7047295   3.2012112 ]
 [ 3.3089955   4.129993  ]]


In [119]:
print saida2

4.977703


Criando pacotes

In [131]:
x1 = np.random.randn(4,8)
w1 = np.random.randn(8,2)

x2 = np.random.randn(4,8)
w2 = np.random.randn(8,2)

x3 = np.random.randn(4,8)
w3 = np.random.randn(8,2)

x4 = np.random.randn(4,8)
w4 = np.random.randn(8,2)

x5 = np.random.randn(4,8)
w5 = np.random.randn(8,2)

lista_x = [x1, x2, x3, x4, x5]
lista_w = [w1, w2, w3, w4, w5]

lista_saida = []

b = tf.random_normal((4,2),0,1)

x = tf.placeholder(tf.float32, shape=(4,8)) #poderia ser none, none
w = tf.placeholder(tf.float32, shape=(8,2)) #poderia ser none, none
operacao = tf.matmul(x,w)+b

maximo = tf.reduce_max(operacao)

In [132]:
with tf.Session() as sess:
    for i in range(5):
        saida = sess.run(maximo, feed_dict = {x: lista_x[i], w: lista_w[i]})
        lista_saida.append(saida)
print(lista_saida)

[3.9086523, 1.6895704, 5.3651266, 2.6853297, 6.6149306]


In [133]:
len(lista_saida)

5

<h3>Tensor board - Não copiei!!!<h3/>